channels:
  - cvxgrp
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - psycopg2
  - sqlalchemy 
  - deap
  - update_checker 
  - tqdm
  - stopit
  - xgboost
  - tpot
  - tensorflow
  
