dependencies:
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - psycopg2
  - sqlalchemy 
  - deap
  - pywin32
  - update_checker 
  - tqdm
  - stopit
  - xgboost
  - tpot
  - h2oai
  - tensorflow
  
